// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyr6RWgV-ynrN0cCiZaog3EskFwhNldW8',
    appId: '1:456312090123:android:db6694d570e3f12484a10e',
    messagingSenderId: '456312090123',
    projectId: 'rivu-4cf24',
    databaseURL: 'https://rivu-4cf24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rivu-4cf24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLWN08bV6_Q4COvbUEsOmNYUWH7gQfUNA',
    appId: '1:456312090123:ios:2fff838ffd4fd3ee84a10e',
    messagingSenderId: '456312090123',
    projectId: 'rivu-4cf24',
    databaseURL: 'https://rivu-4cf24-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rivu-4cf24.firebasestorage.app',
    iosClientId: '456312090123-r2j8tae98cd3778nb7l9svk5h1nnh6eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.rivuV1',
  );
}
